setup calculator wire frames
Victor-chiemerie/math-magicians pull request #2
Opened 2023-02-16 16:21 UTC by Victor-chiemerie

- Delete all the boilerplate from Create React App.
- Create a new directory called components.
- Inside components, create a new Calculator.js file.
- In Calculator.js, create a React component that matches the given Calculator design:
- Implement only JSX and CSS design
- Develop just the UI of the calculator.
   - Use functional components
- Create at least 1 child component
- Test it in the browser; it renders without problems.

2023-02-16 16:47 UTC, roshan-bajgain requested changes
Hi @Victor-chiemerie, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- No linter errors. ✔️
- GitHub flow is followed. ✔️

## Required Changes ♻️
- [ ] Please remove All the boilerplate that got created by the CRA (*texts*, *images*, and *styles*) in public folder.
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-16 16:47 UTC, roshan-bajgain commented on src/components/Calculator.js
> +);
- [ ] According to the project requirement `Calculator.js` should have at least 1 child component. Please implement it.

2023-02-16 16:47 UTC, roshan-bajgain commented on src/App.js
> +    // </div>
- [ ] [Optional] Please remove the commented code as it make the code dirty.

2023-02-16 16:47 UTC, roshan-bajgain commented on src/components/Calculator.css
> +  background-color: rgb(225, 115, 56);
- [ ] Your component should match the following given design: please make sure that it matches the design.
- [ ] Please use the same color on the screen, keyword.
### Your design
![his](https://user-images.githubusercontent.com/81727988/219429748-a4fbe28c-94fb-4e27-b9e2-8d6108d0b968.png)

### Original design
![original](https://user-images.githubusercontent.com/81727988/219429773-a24add9b-8b77-4d4d-a15d-467134d327a6.png)

2023-02-17 02:26 UTC, Owusu-Desmond requested changes
Hi @Victor-chiemerie  :wave: 

You've done well implementing some of the requested changes, but there are still some changes you still need to work on before you move on to the next project but you are almost there.

<img src="https://media1.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif"/>

 ## Highlights :+1: 
:heavy_check_mark: Good commit history.
:heavy_check_mark: No linter errors.
:heavy_check_mark: Your project is well documented


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-17 02:26 UTC, Owusu-Desmond commented on src/components/Calculator.js
> +);
- [ ] As requested by the previous code reviewer, from the project requirement `Calculator.js` should have at least 1 child component. So please make sure that you create a child component for this Calculator component. :pray:

2023-02-17 07:32 UTC, sumairq approved these changes
### Hi @Victor-chiemerie , 

<img src="https://media4.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✔️ Good commit history
✔️Linters are passing
✔️Very professional README
✔️Correct Git flow
✔️Descriptive PR
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-17 07:35 UTC, merged